services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-service
    container_name: auth-service
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: auth-service
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php-local.ini:/usr/local/etc/php/conf.d/php-local.ini
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - mysql_auth

  mysql_auth:
    image: mysql:5.7
    container_name: mysql_auth
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auth_service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "4306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "9090:80"
    environment:
      PMA_HOST: mysql_auth
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - app-network

  nginx_new:
    image: nginx:alpine
    container_name: nginx_new
    restart: unless-stopped
    tty: true
    ports:
      - "90:90"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  mysql_data:
